steps:
  # 1. Build image dengan memasukkan argumen env untuk Vite
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agencyos:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_NEON_DATABASE_URL=$_DATABASE_URL'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=$_GEMINI_KEY'
      - '.'

  # 2. Push image ke Artifact Registry (pakai folder asli Cloud Run)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agencyos:$COMMIT_SHA'

  # 3. Deploy image ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agencyos'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agencyos:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/agencyos:$COMMIT_SHA'

substitutions:
  _DATABASE_URL: ''
  _GEMINI_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY